- id: remove-comments
  name: Remove comments from scriv .md files
  entry: remove-comments
  language: python
  types: [markdown]
  files: ^changelog\.d/.*\.md$
- id: delete-folder
  name: Delete folder for generated content
  entry: delete-folder
  language: python
- id: check-for-approvers
  name: Check approvers are added if needed
  entry: check-for-approvers
  language: python